# configuration from discord, required to get the bot working
# in the server.
discord:
  token: "your-token"
  # status the bot will display on its user profile
  playingStatus: "Lurking in every channel!"
  # URL to be used to invite the bot to a server
  inviteUrl: https://discord.com/oauth2/authorize?client_id=726478988276531212&scope=bot&permissions=19456
  # Invite URL to support server, this will be displayed on the help command
  supportServerUrl: https://discord.gg/PqpjxYG

# bot configuration
bot:
  # the prefix to be used for commands. This is what the bot
  # will use to filter out commands from normal messages
  prefix: "%"
  # color of the border on the embed message sent by the bots, in hex format.
  # https://www.w3schools.com/colors/colors_picker.asp can be used to find hex
  # color values.
  #
  # This value defaults to "0" if left blank, which is the hex value of black
  # (0x000000)
  embedColor: 0xb3ecff
  # color of the border on the error embed messages sent by the bots, in hex
  # format.
  #
  # This value defaults to "0" if left blank, which is the hex value of black
  # (0x000000)
  errorEmbedColor: 0xb40000

database:
  log: true
  driver: postgres
  url: postgresql://postgres:root@localhost:5432/rotom_b?sslmode=disable
